#!/usr/bin/env zsh
#
# .zshenv - Zsh environment file, loaded always.
#
# This file only sets ZDOTDIR to redirect zsh to use XDG-compliant config location.
# The actual environment setup happens in $ZDOTDIR/.zshenv

# ZSH config dir
export ZDOTDIR=$XDG_CONFIG_HOME/zsh