#!/usr/bin/env zsh
#
# .zshenv - Zsh environment file, loaded always.
#
# This file only sets ZDOTDIR to redirect zsh to use XDG-compliant config location.
# The actual environment setup happens in $ZDOTDIR/.zshenv

# Set XDG_CONFIG_HOME with fallback before using it
# This ensures ZDOTDIR is always valid even if XDG_CONFIG_HOME wasn't set by PAM
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

# ZSH config dir
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"