#!/usr/bin/env zsh
#
# .zstyles - Set zstyle settings for plugins that need them.
#

zstyle ':antidote:bundle' use-friendly-names 'yes'

zstyle ':omz:plugins:extract' lazy yes
zstyle ':omz:plugins:aws' lazy yes
