#!/usr/bin/env zsh
#
# $ZDOTDIR/.zshenv - Zsh environment file, loaded always (when ZDOTDIR is set)
#
# This file runs for ALL zsh shells (interactive and non-interactive).
# It sources the common POSIX shell environment.
# Source common shell environment (minimal POSIX setup)
. $HOME/.config/shell/env

