use super::SourceInfo;

/// Generate a PKGBUILD string from a SourceInfo
pub fn generate_pkgbuild(source: &SourceInfo) -> String {
    let cfg = &source.config;

    // Derive srcdir name from the git repo (last path component without .git)
    let repo_name = cfg
        .url
        .trim_end_matches('/')
        .trim_end_matches(".git")
        .rsplit('/')
        .next()
        .unwrap_or(&cfg.name);

    // Format source line
    let source_fragment = if let Some(branch) = &cfg.branch {
        format!("\"git+{}#branch={}\"", cfg.url, branch)
    } else {
        format!("\"git+{}\"", cfg.url)
    };

    // Build commands indented inside build()
    let build_body = build_function_body(repo_name, &cfg.build_commands);

    // Package commands indented inside package()
    let package_body = build_function_body(repo_name, &cfg.package_commands);

    let makedepends_line = dep_array_line("makedepends", &cfg.dependencies);
    let depends_line = dep_array_line("depends", &cfg.runtime_dependencies);

    let mut pkgbuild = format!(
        r#"# Generated by dcli — do not edit manually
pkgname={name}
pkgver=0
pkgrel=1
pkgdesc="{desc}"
arch=('x86_64')
url="{url}"
{makedepends}{depends}source=({source})
sha256sums=('SKIP')

pkgver() {{
    cd "$srcdir/{repo}"
    git describe --long --tags --abbrev=7 2>/dev/null \
        | sed 's/\([^-]*-g\)/r\1/;s/-/./g' \
        || printf "r%s.g%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short=7 HEAD)"
}}

build() {{
{build_body}
}}

package() {{
{package_body}
}}
"#,
        name = cfg.name,
        desc = cfg.description.replace('"', "\\\""),
        url = cfg.url,
        makedepends = makedepends_line,
        depends = depends_line,
        source = source_fragment,
        repo = repo_name,
        build_body = build_body,
        package_body = package_body,
    );

    pkgbuild = pkgbuild.trim_end().to_string();
    pkgbuild.push('\n');
    pkgbuild
}

fn dep_array_line(field: &str, deps: &[String]) -> String {
    if deps.is_empty() {
        return String::new();
    }
    let items: Vec<String> = deps.iter().map(|d| format!("'{}'", d)).collect();
    format!("{}=({})\n", field, items.join(" "))
}

fn build_function_body(repo_name: &str, commands: &[String]) -> String {
    let mut lines = format!("    cd \"$srcdir/{}\"", repo_name);
    for cmd in commands {
        lines.push('\n');
        lines.push_str("    ");
        lines.push_str(cmd);
    }
    lines
}
