#!/usr/bin/env sh

# if in a terminal
if [ -t 0 ]; then
    # other users shouldn't be able to message by default
    mesg n

    # enable colours
   if [ "$(tput colors)" -ge 8 ]; then
    export CLICOLOR=1
    export COLORTERM=truecolor
   fi
fi
