#!/usr/bin/env sh

# Shell color variables generated by wallust
# DO NOT EDIT DIRECTLY - This file is regenerated on wallpaper changes
#
# TEMPLATE SOURCE: ~/.config/wallust/templates/colors-shell.sh
# GENERATED OUTPUT: ~/.config/shell/wallust/colors-shell.sh
# IMPORT IN CONFIG: . ~/.config/shell/wallust/colors-shell.sh

# Base colors
export UI_BACKGROUND="#{{background}}"
export UI_FOREGROUND="#{{foreground}}"

# Standard 16-color palette
export UI_COLOR0="#{{color0}}"
export UI_COLOR1="#{{color1}}"
export UI_COLOR2="#{{color2}}"
export UI_COLOR3="#{{color3}}"
export UI_COLOR4="#{{color4}}"
export UI_COLOR5="#{{color5}}"
export UI_COLOR6="#{{color6}}"
export UI_COLOR7="#{{color7}}"
export UI_COLOR8="#{{color8}}"
export UI_COLOR9="#{{color9}}"
export UI_COLOR10="#{{color10}}"
export UI_COLOR11="#{{color11}}"
export UI_COLOR12="#{{color12}}"
export UI_COLOR13="#{{color13}}"
export UI_COLOR14="#{{color14}}"
export UI_COLOR15="#{{color15}}"

# Semantic color mappings for UI functions
export UI_BASE03="$UI_COLOR0"      # Dark backgrounds
export UI_BASE02="$UI_COLOR8"      # Background highlights
export UI_BASE01="$UI_COLOR8"      # Secondary text, comments
export UI_BASE0="$UI_FOREGROUND"   # Primary text
export UI_BASE1="$UI_COLOR7"       # Optional emphasized text
export UI_BASE3="$UI_COLOR15"      # Lightest text

export UI_YELLOW="$UI_COLOR3"      # Yellow
export UI_ORANGE="$UI_COLOR11"     # Orange
export UI_RED="$UI_COLOR1"         # Red
export UI_MAGENTA="$UI_COLOR13"    # Magenta
export UI_VIOLET="$UI_COLOR5"      # Violet
export UI_BLUE="$UI_COLOR4"        # Blue
export UI_CYAN="$UI_COLOR6"        # Cyan
export UI_GREEN="$UI_COLOR2"       # Green

# Semantic UI color mappings
export UI_PRIMARY="$UI_BLUE"       # Primary actions, info messages, headers
export UI_SUCCESS="$UI_GREEN"      # Success states, completed actions
export UI_ERROR="$UI_RED"          # Error states, critical warnings
export UI_WARNING="$UI_ORANGE"     # Warning states, caution messages
export UI_CAUTION="$UI_YELLOW"     # Attention messages, notices
export UI_SECONDARY="$UI_BASE01"   # Secondary text, subdued information
export UI_SUBTLE="$UI_BASE01"      # Subtle text, tips, secondary info
