#!/bin/zsh
function bw-unlock() {
    BW_SERVER=$(bw status | jaq -r .serverUrl)
    if [ "$BW_SERVER" = "null" ]; then
        echo "Enter the Vault URL:"
        read vault_url
        bw config server $vault_url
    fi

    BW_STATUS=$(bw status | jaq -r .status)
    case "$BW_STATUS" in
    "unauthenticated")
        echo "Logging into BitWarden"
        export BW_SESSION=$(bw login --raw)
        ;;
    "locked")
        echo "Unlocking Vault"
        export BW_SESSION=$(bw unlock --raw)
        ;;
    "unlocked")
        echo "Vault is unlocked"
        ;;
    *)
        echo "Unknown Login Status: $BW_STATUS"
        return 1
        ;;
    esac

    bw sync
}
