#!/bin/zsh
copy-config() {
    if [[ -n "$1" ]]; then
        local source="$1"
        if [[ -n "$2" ]]; then
            local destination="$XDG_CONFIG_HOME/$2"
        else
            local destination="$XDG_CONFIG_HOME"
        fi
        cp -rv "./config/$source" "$destination"
    fi
}
