#!/usr/bin/env zsh
init-zsh-cmd() {
  local cmd="$1"
  local eval_cmd="$2"
  if command -v $cmd >/dev/null 2>&1; then
    if [[ -z "$eval_cmd" ]]; then
      eval "$($cmd init zsh)"
    else
      eval $eval_cmd
    fi
  else
    return 1
  fi
}
