[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[settings.python]
uv_venv_auto = true

[settings.npm]
bun = true

[tools]
# Runner & Package manager
uv = "latest"
bun = "latest"
node = [
    {version = "24"},
    {version="latest"}
]
pnpm = "latest"

# Tools
prettier = "latest"
"npm:playwright" = {version = "latest", postinstall = "playwright install"}

# AI Tools
"claude-code" = "latest"
"npm:opencode-ai" = "latest"
"pipx:oraios/serena" = "latest"
"npm:@fission-ai/openspec" = "latest"
"github:AlexsJones/llmfit" = "latest"
"github:arimxyer/models" = "latest"

# Custom tools
"gitlab:amoconst/twiggit" = "latest"
